### ISSUE TITLE
Fails to connect online

### ISSUE THREAD

**Issue by xathian** [alicealys/tpp-server-emulator#1]
With the server running, I attempt to connect online and the terminal window reads out

[Endpoint] Handling command "CMD_GET_URLLIST"
[Endpoint] Handling command "CMD_GET_SVRLIST"
[Endpoint] Handling command "CMD_GET_SVRTIME"
[Endpoint] Handling command "CMD_GDPR_CHECK"
[Endpoint] Handling command "CMD_AUTH_STEAMTICKET"

Before I get an error in game that I cannot log in to the servers. I figured maybe the steam ticket part was failing as the final step so I created the config.json and toss in

```
{
use_konami_auth : false
}
```

But it still attempts to do the CMD_AUTH_STEAMTICKET step and fails to connect

**Comment by MXYLR** [comment]
I got the same problem, how did you solve it ?
