### ISSUE TITLE
Does this simulate your FOB units being stolen by other players?

### ISSUE THREAD

**Issue by xathian** [alicealys/tpp-server-emulator#2]
I tried this out, managed to finally get it all working except the first thing that started happening was my Units being absolutely decimated. Every minute or so I get warnings that my units are leveling down, I check my menu for Troublemakers, I have none. It keeps leveling down and down and down. I check the Former staff menu and everyone is just piling into here as "Killed or extracted by enemy". I've now lost nearly 400 staff, my units are all nearly 60% lower level now. This screwed my save

**Comment by alicealys** [comment]
This project is unfinished so not everything works or works correctly, fob units being stolen has not been implemented iirc (I haven't worked on this in months), so that is probably a bug. You probably should've made a backup save.
